### ISSUE TITLE
Total number of proposals in progress bar

### ISSUE THREAD

**Issue by haraldng** [TimXLHan/omnipaxos-demo-with-dashboard#12]
It seems like the total number of proposals in the progress bar for some reason don't get updated after a while. E.g., it might show 40000/10000 proposals completed

**Comment by TimXLHan** [comment]
[Here](https://github.com/TimXLHan/omnipaxos-demo-with-dashboard/blob/main/coordinator/src/ui/ui_app/render.rs#L265) we set the `finished / total` value, which are both `u16`. Can check if there is something wrong that leads to number drifting.

**Comment by haraldng** [comment]
yes max of u16 is 65k so it's not a lot. We should change to u64
